name: simple_app_state
description: "A package for state management and state persistence in Flutter apps."
version: 0.0.11
repository: https://github.com/MasahideMori-SimpleAppli/simple_app_state

environment:
  sdk: ^3.9.2
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  file_state_manager: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_lint: ^2.0.0
